# Generated by Django 5.1.2 on 2024-10-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afri_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
